# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - yapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: npm install dependencies
        run:  npm install

      - name: build
        run: npm run build
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: angular-app
          path: yourapp/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: angular-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AA6B7FD930F74DB8A0E072AFB56CCA3E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7422C7529EBD4798AFED1F587875259C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA41377F95594C6DA0161BC14B3E9C29 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'yapp'
          slot-name: 'Production'
          package: ${{ github.workspace }}/angular-app

          
